name: Create Pull Request to Development

on: 
  push:
    branches-ignore:
      - main
      - development

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set branch name variable
        id: set-vars
        run: echo "BRANCH_NAME=${{ github.ref_name }}-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Push the new branch to the remote
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}
          git push origin ${{ env.BRANCH_NAME }} 

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: development
          title: "${{ github.event.head_commit.committer.name }} - title "
          body: "Content commit: ${{ github.event.head_commit.message }}"

  