name: Create Pull Request to Development

on: 
  push:
    branches-ignore:
      - main
      - development

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ github.ref_name }}-${{ github.run_id }}
          base: development
          title: "${{ github.event.head_commit.committer.name }} - title "
          body: "Content commit: ${{ github.event.head_commit.message }}"
          delete-branch: true

  