name: Create Pull Request to Development

on: 
  push:
    branches-ignore:
      - main
      - development

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set branch name variable
        id: set-vars
        run: echo "BRANCH_NAME=${{ github.ref_name }}-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Push the new branch to the remote
        run: |
          git fetch origin ${{ env.ref_name }}
          git checkout -b ${{ env.BRANCH_NAME }} origin/${{ github.ref_name }}
          git push origin ${{ env.BRANCH_NAME }} 

      - name: Debug Branch
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Branches on remote:"
          git branch -r
          git log --oneline -5

      - name: Check if there are changes
        run: |
          if git diff --quiet origin/development...${{ env.BRANCH_NAME }}; then
            echo "No changes detected. Skipping PR creation."
            exit 0
          fi
  

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN_PAT }}
          branch: ${{ env.BRANCH_NAME }}
          base: development
          title: "${{ github.event.head_commit.committer.name }} - title "
          body: "Content commit: ${{ github.event.head_commit.message }}"

  