name: Deploy to Development

on: 
  push:
    branches-ignore:
      - main
      - development

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: development
          title: "${{ github.event.head_commit.title }}"
          body: "Content commit: {{ github.event.head_commit.message}}"
          delete-branch: true

  build-and-test:
    needs: create-pull-request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build

    merge-if-success:
      needs: build-and-test
      runs-on: ubuntu-latest
      if: success()
      steps:
        - name: Merge PR
          uses: pascalgn/automerge-action@v0.15.5
          with: 
            github-token: ${{ secrets.GITHUB_TOKEN }}
            merge-method: squash

    request-review-if-fail:
      needs: build-and-test
      runs-on: ubuntu-latest
      if: failure()
      steps:
        - name: Request Review
          uses: hmarr/auto-approve-action@v3
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}

        - name: Send Email Notification
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: "ORDERIZE - Site | Review Required PULL REQUEST"
            body: "O Build do site falhou. Por favor faça uma revisão na Pull Request."
            to: "${{ github.event.pusher.email }}"
            from: "CI/CD Bot"