name: Create Pull Request to Development

on: 
  push:
    branches-ignore:
      - main
      - development

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set PR body template
        id: set-pr-template
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"

          # Criando o corpo do PR com a mensagem do commit e incluindo as quebras de linha corretamente
          PR_BODY="## Descrição\nDescreva brevemente o que foi desenvolvido e por que.\n- $COMMIT_MESSAGE\n\n## Observações\nInclua quaisquer outras informações relevantes que possam ser úteis para a revisão do PR.\n-"
          
          # Salvando o corpo do PR corretamente como variável de ambiente
          echo "PR_BODY<<EOF" >> $GITHUB_ENV
          echo -e "$PR_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: GitHub CLI login
        run: |
          echo "${{ secrets.TOKEN_PAT }}" | gh auth login --with-token

      - name: Edit or Crete Pull Request
        run: |
            PR_URL=$(gh pr list --base development --head ${{ github.ref_name }} --json url -q '.[0].url')
            if [ -n "$PR_URL" ]; then
              echo "Updating existing PR: $PR_URL"
              gh pr edit $PR_URL --body "${{ env.PR_BODY }}"
            else
              echo "No existing PR found, creating a new one."
              gh pr create --base development --head ${{ github.ref_name }} --title "Pull Request from ${{ github.ref_name }} to development | ${{ github.event.head_commit.committer.name }}" --body "${{ env.PR_BODY }}"
            fi
        