name: Merging with development branch

on:
  workflow_run:
    workflows: ["Create Pull Request to Development", "Building and Testing"]
    types: 
      - completed

jobs:
  merge-if-success:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success() 
    steps:
      - name: Merge PR
        uses: pascalgn/automerge-action@v0.15.5
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
